### ISSUE TITLE
Parsing is not working on trivial examples that work as a configuration file in play.

### ISSUE THREAD

**Issue by Ktedon** [lambdista/config#24]
I have a simple config file that the library is failing to parse on the first line. My code is this:
```scala
package controllers

import scala.concurrent.duration.Duration
import java.nio.file.Paths
import com.lambdista.config._
import ciris.refined._

object Configuration {

	private val confPath: String = "conf/application.conf"
	private var config: Result[Config] = Config.from(Paths.get(confPath))

	@inline // true on success
	def configResult: Boolean = {
		config match {
			case Right(success) => 
				println(success)
				return true
			case Left(failure)  => 
				println("\n" + failure.toString)
				return false
		}
	}
}
```
This will return a left() failure with the failure.toString returning "com.lambdista.config.ConfigSyntaxError: Position 3:1, found "play {\n  a"". The config file starts as 
```
play {
  assets {
    path = "/public"
    urlPrefix = "/assets"
  }
}
```

Am I doing something wrong here or is this a bug?

**Comment by lambdista** [comment]
You're trying to use HOCON syntax and, for that, you need the config-typesafe module. Here is the doc: https://github.com/lambdista/config#typesafeLoader

I also added a test for this issue: https://github.com/lambdista/config/blob/master/typesafe/src/test/scala/com/lambdista/config/TypesafeConfigSuite.scala#L80
